server:
  port: 7500

#dubbo
dubbo:
  application:
    name: demoService
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://127.0.0.1:2181

# log
logging:
  level:
    com.example.dubboweb: DEBUG
  file: D:\logs\dubbo-web.log

